version: "3.7"
services:
  FakeDns:
    container_name: FakeDns
    image: python:3.8
    working_dir: /opt/FakeDns/
    command: /opt/FakeDns/fakedns.py -c /opt/FakeDns/dns.conf.example
    volumes:
      - ./:/opt/FakeDns
    ports: 
      - "127.0.0.1:15353:53/udp"
